
package CapaPresentacion;

import CapaNegocio.Director;
import CapaNegocio.Estudiante;
import CapaNegocio.Profesor;
import java.util.ArrayList;
import javax.swing.JOptionPane;


public class FrmComunidadUniver extends javax.swing.JFrame {
    ArrayList<Director> ar;

    //Director objD = new Director("","");
    //Estudiante objE = new Estudiante("","");
    //Profesor objP = new Profesor("","");
    
    public FrmComunidadUniver() {
        
        initComponents();
        txtNh.setEnabled(false);
        txtProm.setEnabled(false);
        txtape.setEnabled(false);
        txtco.setEnabled(false);
        txtcod.setEnabled(false);
        ar = new ArrayList<Director>();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        txtProm = new javax.swing.JTextField();
        txtNh = new javax.swing.JTextField();
        txtcod = new javax.swing.JTextField();
        txtape = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtco = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstresul = new javax.swing.JTextArea();
        rbDirector = new javax.swing.JRadioButton();
        rbEstudiante = new javax.swing.JRadioButton();
        rbProfesor = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtcod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcodActionPerformed(evt);
            }
        });

        jLabel2.setText("CODIGO :");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Comunidad Universitaria");

        txtco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcoActionPerformed(evt);
            }
        });

        jButton1.setText("Grabar y Mostrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel6.setText("Promedio Final :");

        jLabel5.setText("Numero de Horas :");

        jLabel4.setText("Numero de Oficina :");

        jLabel3.setText("APELLIDO :");

        lstresul.setColumns(20);
        lstresul.setRows(5);
        jScrollPane1.setViewportView(lstresul);

        buttonGroup1.add(rbDirector);
        rbDirector.setText("Director");
        rbDirector.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                rbDirectorStateChanged(evt);
            }
        });

        buttonGroup1.add(rbEstudiante);
        rbEstudiante.setText("Estudiante");
        rbEstudiante.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                rbEstudianteStateChanged(evt);
            }
        });
        rbEstudiante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbEstudianteActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbProfesor);
        rbProfesor.setText("Profesor");
        rbProfesor.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                rbProfesorStateChanged(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(rbDirector)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jLabel4)
                                                .addComponent(jLabel3)
                                                .addComponent(jLabel5))
                                            .addGap(2, 2, 2))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel6)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel2)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(txtape, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtco, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(txtProm, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtNh, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtcod, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(86, 86, 86)
                                            .addComponent(rbProfesor)
                                            .addGap(10, 10, 10))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(rbEstudiante)
                                            .addGap(9, 9, 9)))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(126, 126, 126)
                                .addComponent(jLabel1))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(7, 7, 7)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtape, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtcod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(rbEstudiante)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rbDirector)))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtNh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rbProfesor))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtProm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtcodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcodActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcodActionPerformed

    private void txtcoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcoActionPerformed

    private void rb(){
        if (rbEstudiante.isSelected()){
            txtNh.setEnabled(false);
            txtProm.setEnabled(true);
            txtape.setEnabled(true);
            txtco.setEnabled(true);
            txtcod.setEnabled(false);
           
       }else if(rbDirector.isSelected()){
            txtNh.setEnabled(false);
            txtProm.setEnabled(false);
            txtape.setEnabled(true);
            txtco.setEnabled(true);
            txtcod.setEnabled(true);
       }else if(rbProfesor.isSelected()){
            txtNh.setEnabled(true);
            txtProm.setEnabled(false);
            txtape.setEnabled(true);
            txtco.setEnabled(true);
            txtcod.setEnabled(false);
       }else{
            txtNh.setEnabled(false);
            txtProm.setEnabled(false);
            txtape.setEnabled(false);
            txtco.setEnabled(false);
            txtcod.setEnabled(false);
       }
    } 
            
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         if(rbDirector.isSelected()){
             //Guardando Atributos
            //objD.setCodOf();
            //objD.setApe(txtape.getText());
            //objD.setCod(txtco.getText());
            
            //Director objD=new Director(txtco.getText(), txtape.getText(), txtcod.getText());
            
            ar.add(new Director(txtco.getText(), txtape.getText(), txtcod.getText()));
            
            
            
            //Mostrando Atributos
             for (Director obj : ar) {
                    JOptionPane.showMessageDialog(null, "Codigo : "+obj.getCod()+"\nApellido : "+obj.getApe()+"\nCodigo de Oficina : "+obj.getCodOf());

             }
        }
        
        if(rbProfesor.isSelected()){
            
            //objP.setNh(Integer.parseInt(txtNh.getText()));
            //objP.setApe(txtape.getText());
            //objP.setCod(txtco.getText());
            
            Profesor objP=new Profesor(txtco.getText(), txtape.getText(), Integer.parseInt(txtNh.getText()));
            
            JOptionPane.showMessageDialog(null, "Codigo : "+objP.getCod()+"\nApellido : "+objP.getApe()+"\nNumero de Horas : "+objP.getNh());
        }
        if(rbEstudiante.isSelected()){
            
            //objE.setPromF(Double.parseDouble(txtProm.getText()));
            //objE.setApe(txtape.getText());
            //objE.setCod(txtco.getText());
            
            Estudiante objE=new Estudiante(txtco.getText(), txtape.getText(), Double.parseDouble(txtProm.getText()));
            
            JOptionPane.showMessageDialog(null, "Codigo : "+objE.getCod()+"\nApellido : "+objE.getApe()+"\nPromedio Final : "+objE.getPromF());
        
        }
        limpiar();
    }//GEN-LAST:event_jButton1ActionPerformed

    public void limpiar()
    {
       txtNh.setText("");
       txtProm.setText(""); 
       txtape.setText(""); 
       txtco.setText("");
       txtcod.setText("");
    }
    
    private void rbEstudianteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbEstudianteActionPerformed
       
    }//GEN-LAST:event_rbEstudianteActionPerformed

    private void rbEstudianteStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_rbEstudianteStateChanged
        rb();
    }//GEN-LAST:event_rbEstudianteStateChanged

    private void rbDirectorStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_rbDirectorStateChanged
        rb();
    }//GEN-LAST:event_rbDirectorStateChanged

    private void rbProfesorStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_rbProfesorStateChanged
        rb();
    }//GEN-LAST:event_rbProfesorStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmComunidadUniver.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmComunidadUniver.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmComunidadUniver.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmComunidadUniver.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmComunidadUniver().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea lstresul;
    private javax.swing.JRadioButton rbDirector;
    private javax.swing.JRadioButton rbEstudiante;
    private javax.swing.JRadioButton rbProfesor;
    private javax.swing.JTextField txtNh;
    private javax.swing.JTextField txtProm;
    private javax.swing.JTextField txtape;
    private javax.swing.JTextField txtco;
    private javax.swing.JTextField txtcod;
    // End of variables declaration//GEN-END:variables
}
